# Generated by Django 4.0.3 on 2022-04-14 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Picture',
        ),
    ]
